### ISSUE TITLE
Any working dual/tri card PCI-e cxadc setups?

### ISSUE THREAD

**Issue by happycube** [happycube/cxadc-linux3#22]
I've tried with the 'green' CX PCI-e cards in two different Haswell systems and only one card can be seen at a time.  Are there any (hopefully affordable) motherboard/CX-pci-e card combos that do work?

**Comment by harrypm** [comment]
As discussed and shown on the discord this should be noted here too :)
Multi-Card and Live Gain change able version:
https://gitlab.com/jorgem-dev/cx88_sdr

DD86 Discord Message Points:
https://discord.com/channels/665557267189334046/665834485975351307/969003622539071539
https://discord.com/channels/665557267189334046/676084498097766451/969410706489360405

**Comment by harrypm** [comment]
This is now been made a non-issue with the last commit #34 and the availability of both Asmedia/ITE PCIe 1x cards eliminate any hardware compatibility issues that have been found so I'll close this.
