### ISSUE TITLE
Useless sox command in FLAC compression guide?

### ISSUE THREAD

**Issue by kasamikona** [happycube/cxadc-linux3#38]
On the [FLAC Compression Guide](https://github.com/happycube/cxadc-linux3/wiki/FLAC-Compression-Guide) wiki page, as well as a few snippets near the bottom of README.md, the realtime compression examples all currently start with a sox command of the form:
`sox -r <rate> -b 8 -c 1 -e unsigned -t raw /dev/cxadc0 -t raw -`.

This appears to do nothing except maybe waste a bit of CPU time. As no output format is set, it just outputs the same data.
Is it supposed to be doing some resampling or something? If not, is there any reason to favor this over a simple `cat /dev/cxadc0 | flac ...`?

**Comment by harrypm** [comment]
These commands are meant to define a specific decimal rate for the flac file, though these are all oriented around saving media FM data such as vhs/Betamax etc for [vhs-decode](https://github.com/oyvindln/vhs-decode#readme) which is why this driver is maintained, there are many ways you can go about compressing and formatting the data this is just a format which the decoders accept and such is practical.

**Comment by kasamikona** [comment]
I understand the tagging of the sample rate (/1000) for the final flac file. That's tagged perfectly well by the `flac` command with `--sample-rate=`. Up until that point it's raw data. `sox` is dealing with raw data in and raw data out, so it has no way to tag anything with a sample rate.

The output is the same with cat.

```
$ echo -ne "\x11\x22\x33\x44\x55\x66" > DUMMYFILE

$ sox -r 28636 -b 8 -c 1 -e unsigned -t raw DUMMYFILE -t raw - | flac --fast -16 --sample-rate=28636 --sign=unsigned --channels=1 --endian=little --bps=8 --blocksize=65535 --lax -f - -o withsox.flac

$ cat DUMMYFILE | flac --fast -16 --sample-rate=28636 --sign=unsigned --channels=1 --endian=little --bps=8 --blocksize=65535 --lax -f - -o withcat.flac

$ sha1sum *.flac
00a7302853c2ea4ed918a432c66cac8030b15fe7  withcat.flac
00a7302853c2ea4ed918a432c66cac8030b15fe7  withsox.flac
```

I noticed this when setting up my vhs-decode scripts.

**Comment by harrypm** [comment]
@kasamikona Okay I started reviewing the commands as today I have been updating stuff like adding windows flac compression scripts.

Yeah I'll update the commands in the wiki this makes sence!
