### ISSUE TITLE
worked on ubuntu great; not so much on Mint 

### ISSUE THREAD

**Issue by steveseguin** [happycube/cxadc-linux3#46]
The VHS-Decode guide recommends using Mint linux, however I see that your guide is tested for Ubuntu.

Well, I tried Mint first, but had issues with the driver not building/installing.

There was error an `arch/x86/Makefile: CONFIG_X86_X32 enabled but no binutils support` during the make step, and I couldn't figure out a solution. It might not have been the cause, but no cx device driver appeared in /dev/ regardless.

Anyways, I switched to Ubuntu 22 and it worked wonderfully; no CONFIG_X86_X32 error and the cx driver appears.

Thank you very kindly for this driver. 💖 I'm looking forward to the day its available as a pcie-pass thru on WSL2 or a native windows driver; or maybe as a Raspberry Pi 5 PCIe driver. =D  I could embed the entire capture system into the VHS box itself in that case. One can dream.

**Comment by harrypm** [comment]
@steveseguin What exact version of mint did you try? (Its basically Ubuntu without a lot of little issues hence why its recommended)

**Comment by steveseguin** [comment]
[linuxmint-21.2-cinnamon-64bit.iso](https://muug.ca/mirror/linuxmint/iso/stable/21.2/linuxmint-21.2-cinnamon-64bit.iso)

I installed it twice, so while I perhaps did something wrong, it worked effortlessly on Ubuntu 22 first try.

I'm running an old AMD bulldozer desktop, just for this vhs-decode build, if that helps at all.


Feel free to close the ticket;  I prefer Ubuntu really anyways, so its no issue here.

**Comment by harrypm** [comment]
Just confirmed this on a fresh install yeah this is a bug that needs to be sorted.

**Comment by harrypm** [comment]
Currently there is 2 works arounds for this is using the [xanmod](https://xanmod.org/) kearnal or installing binutils via `apt install binutils` so I'll close this and update the readme @steveseguin
