### ISSUE TITLE
Blacklist Additional Kernel Modules in cxadc.conf

### ISSUE THREAD

**Issue by titan-91** [happycube/cxadc-linux3#8]
I have different types of CX2388 based PCI cards and kept running into errors when trying to access the device after switching out different cards. The error was "no such device or address." Although the /dev/cxadc0 special device file was being created fine, the cxadc kernel module was not loading even though insmod was not giving any errors. By running lsmod, I found several additional stock kernel modules were loading at boot and causing a conflict with cxadc. I blacklisted the additional modules and my cxadc.conf file now looks like this:

blacklist cx88_alsa
blacklist cx8800
blacklist cx88xx
blacklist cx8802
blacklist cx88_blackbird
blacklist cx2341x

This may be an issue for others with different types of cards, and would probably be good to add to xcadc.conf in the main repository. There may be other stock modules as well that I'm not aware of.

**Comment by happycube** [comment]
Done, thanks!
